### ISSUE TITLE
page.posts is not site.posts

### ISSUE THREAD

**Issue by igorw** [pattex/jekyll-tagging#13]
Index templates use `site.posts`, but this plugin stores the posts in `page.posts`. This is really annoying because in order to re-use templates, I need to do:

    {% if page.posts %}
        {% assign posts = page.posts %}
    {% else %}
        {% assign posts = site.posts %}
    {% endif %}

    {% for post in posts %}
        ...
    {% endfor %}

Unless there is a better way to do it -- but I didn't find one.

Ideally they would both just store it in `site.posts`.

**Comment by alexunder** [comment]
{% if post.category not contains 'blog'%}
   some actions
{% endif %}

There is any mistake in the code snippet above? The github send me a page build error. I can't fix it. Thanks!

**Comment by pattex** [comment]
@alexunder I think this is a Jekyll may be Liquid related question and not at all topic of this issue. And to be honest, I don't know. I just didn't work a lot with Jekyll the last two years.
