### ISSUE TITLE
Name and slug

### ISSUE THREAD

**Issue by luixxiul** [pattex/jekyll-tagging#15]
It'd be nice if I could set names and slugs of each tag, so that I could automatically show the title different from the slug itself. I'm deploying it manually by doing like this:
```
{% if page.tag == 'food' %}
    <h2>Favorite Food</h2>
{% elseif page.tag == 'place' %}
    <h2>Favorite Place</h2>
{% else %}
   <h2>{{ page.tag }}</h2>
{% endif %}
```
Or anyone knows how to handle it by tweating liquid tags?

**Comment by nhoizey** [comment]
It could look for a YAML data file that would match slugs and names…

**Comment by pattex** [comment]
Yup, I'd do it like @nhoizey suggests, I think.

**Comment by nhoizey** [comment]
Wait. You closed the issue, but did you implement it yet?

**Comment by pattex** [comment]
It may be my crappy english, but this is a misunderstanding.
I meant to say that I would do it this way if I would implement it. But I will not. I want to keep it super simple and just use the tagging like Jekyll implements it without bells and whistles.

**Comment by nhoizey** [comment]
Ok, sorry, I misunderstood indeed.
