### ISSUE TITLE
[Feature] Allow spaces to be escaped in URLs

### ISSUE THREAD

**Issue by rileyjshaw** [pattex/jekyll-tagging#27]
For tags like:
```ruby
tags:
 - multi word
 - other tag
```
URLs show up as:

```
http://site.com/path/multi%20word/     # pretty
````

or as:

```
http://site.com/path/other%20tag.html  # default
```

It would be great to have the option of formatting them with hyphens, underscores, etc. like:

```
http://site.com/path/multi-word/
```

or:

```
http://site.com/path/other_tag.html
```

or even just eliminating spaces from the URL completely...

**Comment by nhoizey** [comment]
I agree. And I think hyphens would be the best for SEO.

**Comment by rileyjshaw** [comment]
@pattex any thoughts?

**Comment by pattex** [comment]
Done. You may want to check if it works out for you, if the delay was not to big.

**Comment by rileyjshaw** [comment]
@pattex thanks for looking into this! It doesn't seem to be working with `tag_permalink_style: pretty`, am I missing something?

**Comment by pattex** [comment]
You are absolutely right. I fixed that.

**Comment by rileyjshaw** [comment]
Just tested it out, seems to be working. Thanks!!
