### ISSUE TITLE
Not working on Github

### ISSUE THREAD

**Issue by dblock** [pattex/jekyll-tagging#29]
I am probably doing something wrong, this plugin worked with Jekyll 2.5 locally for me, but is failing on Github. Doesn't generate anything in tag/*.

If I add `jekyll-tagging` to gems I get " `require': cannot load such file -- jekyll-tagging", this makes sense since that doesn't exist and should be jekyll/tagging. We can fix this here if that's the right thing to do.

However just copying jekyll/tagging.rg into _plugins works locally, but doesn't do anything on Github.

What's the right way to set this up?

My code: https://github.com/dblock/code

**Comment by pattex** [comment]
As far as I know, Github Pages doesn't support custom plugins.
https://help.github.com/articles/using-jekyll-plugins-with-github-pages/

**Comment by dblock** [comment]
Thanks, I figured that later ;(
