### ISSUE TITLE
Posts with identical tags produce multiple entries on tag page

### ISSUE THREAD

**Issue by efung** [pattex/jekyll-tagging#31]
I'm using `jekyll-tagging `0.6.0`. I have a post with this:

`tags: [Homebaking, banana, quick bread, banana]`

This causes two entries for the post to show up on the generated `/tag/banana` page. 

The tag array should be run through `uniq!` or something like that.

The workaround is to just remove the duplicate tag from the post, obviously.

**Comment by pattex** [comment]
Sorry for that huge delay. It seems to me like this behaviour is related to Jekyll itself.
