### ISSUE TITLE
tag_page_dir and baseurl don't play together

### ISSUE THREAD

**Issue by martinpaljak** [pattex/jekyll-tagging#32]
{{ post | tags }} generates links with  /tag/foo/ no matter what I set the folder to (baseurl being /new in my case, tried using /new/tag but that did not work either). Tag indexes are generated correctly to /new/tag/foo/index.html, just the links are incorrect.

**Comment by pattex** [comment]
I know, I'm super late. Sorry for that.
I don't know if I understand the problem right, but could you please take a look at issue #20 if this is what you want.
