### ISSUE TITLE
Remove accents from slugs

### ISSUE THREAD

**Issue by nhoizey** [pattex/jekyll-tagging#34]
I have a tag that is the french word « vidéo ». It is kept as is for the tag page, so I have a `tags/vidéo.html` file.

When I deploy it, there are issues.

The link in the tags cloud is `/tags/vid%C3%A9o.html`, the browser —I use Firefox on a Mac— shows `/tags/vidéo.html` in the URL bar, but the server answers with a 404 error, `The requested URL /tags/vidÃ©o.html was not found on this server.`

It would be very nice if the plugin could let me use the « vidéo » tag in my posts, but generate a `tags/video.html` page, without the accent.

**Comment by nhoizey** [comment]
I fixed the issue with the encoding, adding `--iconv=UTF8-MAC,UTF-8` to my `rsync` command.

But I really would like to be able to have slugs without accents.

**Comment by pattex** [comment]
Done. You may want to check if it works out for you, too.

**Comment by nhoizey** [comment]
It works, thanks a lot!
