### ISSUE TITLE
Regenerate tags?

### ISSUE THREAD

**Issue by fernand0** [pattex/jekyll-tagging#41]
I'm using jekyll-tagging in a local clone in order to generate tags. Then I copy them to the github site as if they were static pages (because github does not allow plugins). From time to time, jekyll-tags is missing some tags and I'm wondering if there is a way to re-generate the tags for the whole site in order to recover the missing tags. Or, maybe, re-generating tags for some posts.
Thanks for any hints!

**Comment by gingerbeardman** [comment]
How did you end up doing this?

**Comment by fernand0** [comment]
Not done, sorry.
