### ISSUE TITLE
generate a /tag/index.html

### ISSUE THREAD

**Issue by chrylis** [pattex/jekyll-tagging#43]
The `/tag/` directory has no index, which produces either a Forbidden or a directory listing. It would be nice to have something there, either a configurable page or just a default-layout page with the tag cloud as the content.

**Comment by nhoizey** [comment]
Here is the page I generate:
https://nicolas-hoizey.com/tags/

Here is the source:
https://github.com/nhoizey/nicolas-hoizey.com/blob/master/tags/index.html

**Comment by ParthKolekar** [comment]
@nhoizey how did you get this working? 

I created a tag directory, but tag/index.html is being copied verbatim.

**Comment by 0xdevalias** [comment]
From the [README](https://github.com/pattex/jekyll-tagging)

> Now you have a new filter called tag_cloud which you can use with the site object as argument in your layout to get a cloud of all your site's tags.

**Comment by ParthKolekar** [comment]
Oh I got my problem. 

my tag/index.html had this content 

    --
      layout: home
      permalink: /tag/
      title: Tag
    --
    
    <div class="tagscloud">
      {{ site | tag_cloud }}
    </div>

Do you see the error here? 
The there are only two dashes. :sob: :sob: 
I wasted an entire day, only to realize that there need to be three dashes in my file.

**Comment by 0xdevalias** [comment]
Hahaha! The modern evolution of the missing ; problem :p

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by nhoizey** [comment]
@ParthKolekar sorry you wasted a full day! ;-)

**Comment by ParthKolekar** [comment]
None of it was your fault.
