### ISSUE TITLE
nuggets "Please update your dependencies."

### ISSUE THREAD

**Issue by ke352802081770314** [pattex/jekyll-tagging#45]
when saying "gem install jekyll-tagging" I got this message, which I am passing on:

ruby-nuggets-1.0.0 [2014-06-20]:
* This project has been renamed to +nuggets+. Please update your dependencies.

The version it installed for me is jekyll-tagging-1.0.1 [2015-06-11].

**Comment by pattex** [comment]
Done. a981f78

Thanks a lot and greetings
pattex - the worst open source maintainer of the galaxy
