### ISSUE TITLE
AGPL

### ISSUE THREAD

**Issue by arokettu** [pattex/jekyll-tagging#50]
gem nuggets is licensed under Affero GPL which is quite infectious. it is necessary to clearly mark this or to get rid of nuggets dependency

**Comment by hazzik** [comment]
@sandfoxme apparently they don't care: #21

**Comment by arokettu** [comment]
@hazzik I'm not proposing the license change, just place a note somewhere that the library depends on AGPL lib
btw I think that license change will be harmful. Currently anyone can fork jekyll-tagging, remove all nuggets calls and use it as an apgl-free gem

**Comment by arokettu** [comment]
closing because I no longer care
