### ISSUE TITLE
Title of tag page

### ISSUE THREAD

**Issue by francisdotbio** [pattex/jekyll-tagging#52]
Hi, 
I need the tag title in my default layout like this: `<title>Tag title - Blog title</title>`
for post we have:

    {% if page.title %}
      {{ page.title | escape }} - {{ site.title | escape }}
    {% else %}
      {{ site.title | escape }}
    {% endif %}

but how can I add if it was page.tag ?

**Comment by francisdotbio** [comment]
Well, Actually I fixed it without using the default layout.
```
---
layout: nil
---
<!DOCTYPE html>
<html lang="en">
{% include head.html %}

<title> {{ page.tag }} - {{ site.title | escape }} </title>

<body>
    {% include header.html %}
    <section class="content">
        <h2 class="notes-title">{{ page.tag }}</h2>
        <ul class="note-list">
            {% for post in page.posts %}
            <li>
                <h2><a href="{{ post.url | prepend: site.baseurl }}">{{ post.title }}</a></h2>
                <time datetime="{{post.date | date: '%Y-%m-%d'}}" itemprop="datePublished">{{post.date | date: '%Y-%m-%d'}}</time>
            </li>
            {% endfor %}</ul>
    </section>
    {% include footer.html %}
</body>
</html>
```

**Comment by Vallek** [comment]
I know it's old, but if someone like me still needs it) You can edit one line in jekyll-tagging gem.

Find Ruby: `where ruby`

Gems are at: `Ruby\lib\ruby\gems\version\gems\`

Open `jekyll-tagging-1.1.0\lib\jekyll\tagging.rb`

Find
```
data = { 'layout' => layout, 'posts' => posts.sort.reverse!, 'tag' => tag }
```

and change it to something like:
```
data = { 'layout' => layout, 'posts' => posts.sort.reverse!, 'tag' => tag, 'title' => 'Posts about' + ' ' + tag }
```
